export default function Footer() {
  return (
    <footer className="site-footer">
      <div className="container">
        <div className="footer-top">
          <div className="logo" style={{ color: '#1c1c1c' }}>
            Dine.AI
          </div>
          <p className="footer-tagline">AI-powered restaurant recommendations</p>
        </div>
        <div className="footer-copy">
          Recommendations are generated by our AI engine using real restaurant data.
          © {new Date().getFullYear()} Dine.AI
        </div>
      </div>
    </footer>
  )
}
